"""Changed table user

Revision ID: 340c0542ccd0
Revises: 2e9a45385067
Create Date: 2021-11-06 18:28:51.948822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '340c0542ccd0'
down_revision = '2e9a45385067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=240),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=240),
               type_=mysql.VARCHAR(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###
