"""Changed table post

Revision ID: 91428d0f227a
Revises: a331034c4127
Create Date: 2021-11-13 22:59:29.132725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91428d0f227a'
down_revision = 'a331034c4127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img_name')
    # ### end Alembic commands ###
