"""Changed table post

Revision ID: a331034c4127
Revises: f00aa224e510
Create Date: 2021-11-13 22:01:35.959320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a331034c4127'
down_revision = 'f00aa224e510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_slug', table_name='post')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', mysql.VARCHAR(length=140), nullable=False))
    op.create_index('ix_post_slug', 'post', ['slug'], unique=False)
    # ### end Alembic commands ###
