"""Changed table user

Revision ID: e72f3e9eb8c7
Revises: 91428d0f227a
Create Date: 2021-11-14 14:48:04.357258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72f3e9eb8c7'
down_revision = '91428d0f227a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_path', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('avatar_name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_name')
    op.drop_column('user', 'avatar_path')
    # ### end Alembic commands ###
