"""Changed table post

Revision ID: f00aa224e510
Revises: c68aee9eb8e7
Create Date: 2021-11-13 20:23:00.996666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00aa224e510'
down_revision = 'c68aee9eb8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('intro', sa.String(length=360), nullable=False))
    op.add_column('post', sa.Column('img_path', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img_path')
    op.drop_column('post', 'intro')
    # ### end Alembic commands ###
